package se.umu.cs.graphql;

import java.util.*;

public interface UpdateEnterpriseMembersCanViewDependencyInsightsSettingMutation {

    UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload updateEnterpriseMembersCanViewDependencyInsightsSetting(UpdateEnterpriseMembersCanViewDependencyInsightsSettingInput input) throws Exception;

}