package se.umu.cs.graphql;

import java.util.*;

public interface UpdateEnterpriseTwoFactorAuthenticationRequiredSettingMutation {

    UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload updateEnterpriseTwoFactorAuthenticationRequiredSetting(UpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput input) throws Exception;

}