package se.umu.cs.graphql;

import java.util.*;

public interface UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingMutation {

    UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload updateEnterpriseMembersCanChangeRepositoryVisibilitySetting(UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput input) throws Exception;

}