package se.umu.cs.githubtypes;

public enum OrgRemoveMemberAuditEntryReason {

    SAML_EXTERNAL_IDENTITY_MISSING, 
    SAML_SSO_ENFORCEMENT_REQUIRES_EXTERNAL_IDENTITY, 
    TWO_FACTOR_REQUIREMENT_NON_COMPLIANCE

}