package se.umu.cs.githubtypes;

public interface RegenerateEnterpriseIdentityProviderRecoveryCodesMutation {

    RegenerateEnterpriseIdentityProviderRecoveryCodesPayload regenerateEnterpriseIdentityProviderRecoveryCodes(RegenerateEnterpriseIdentityProviderRecoveryCodesInput input) throws Exception;

}