package se.umu.cs.githubtypes;

public interface UpdateEnterpriseTwoFactorAuthenticationRequiredSettingMutation {

    UpdateEnterpriseTwoFactorAuthenticationRequiredSettingPayload updateEnterpriseTwoFactorAuthenticationRequiredSetting(UpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput input) throws Exception;

}