package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanDeleteRepositoriesSettingMutation {

    UpdateEnterpriseMembersCanDeleteRepositoriesSettingPayload updateEnterpriseMembersCanDeleteRepositoriesSetting(UpdateEnterpriseMembersCanDeleteRepositoriesSettingInput input) throws Exception;

}