package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingMutation {

    UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingPayload updateEnterpriseMembersCanChangeRepositoryVisibilitySetting(UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput input) throws Exception;

}