package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanDeleteIssuesSettingMutation {

    UpdateEnterpriseMembersCanDeleteIssuesSettingPayload updateEnterpriseMembersCanDeleteIssuesSetting(UpdateEnterpriseMembersCanDeleteIssuesSettingInput input) throws Exception;

}