package se.umu.cs.githubtypes;

public interface UpdateEnterpriseRepositoryProjectsSettingMutation {

    UpdateEnterpriseRepositoryProjectsSettingPayload updateEnterpriseRepositoryProjectsSetting(UpdateEnterpriseRepositoryProjectsSettingInput input) throws Exception;

}