package se.umu.cs.githubtypes;

public interface UpdateEnterpriseDefaultRepositoryPermissionSettingMutation {

    UpdateEnterpriseDefaultRepositoryPermissionSettingPayload updateEnterpriseDefaultRepositoryPermissionSetting(UpdateEnterpriseDefaultRepositoryPermissionSettingInput input) throws Exception;

}