package se.umu.cs.githubtypes;

public interface UpdateEnterpriseAllowPrivateRepositoryForkingSettingMutation {

    UpdateEnterpriseAllowPrivateRepositoryForkingSettingPayload updateEnterpriseAllowPrivateRepositoryForkingSetting(UpdateEnterpriseAllowPrivateRepositoryForkingSettingInput input) throws Exception;

}