package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingMutation {

    UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingPayload updateEnterpriseMembersCanUpdateProtectedBranchesSetting(UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingInput input) throws Exception;

}