package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanMakePurchasesSettingMutation {

    UpdateEnterpriseMembersCanMakePurchasesSettingPayload updateEnterpriseMembersCanMakePurchasesSetting(UpdateEnterpriseMembersCanMakePurchasesSettingInput input) throws Exception;

}