package se.umu.cs.githubtypes;

public interface UpdateEnterpriseMembersCanViewDependencyInsightsSettingMutation {

    UpdateEnterpriseMembersCanViewDependencyInsightsSettingPayload updateEnterpriseMembersCanViewDependencyInsightsSetting(UpdateEnterpriseMembersCanViewDependencyInsightsSettingInput input) throws Exception;

}