package se.umu.cs.githubtypes;

public interface UpdateEnterpriseActionExecutionCapabilitySettingMutation {

    UpdateEnterpriseActionExecutionCapabilitySettingPayload updateEnterpriseActionExecutionCapabilitySetting(UpdateEnterpriseActionExecutionCapabilitySettingInput input) throws Exception;

}